server:
  port: 80

wx:
  mp:
    app-id: @wxMpAppId@
    secret: @wxMpSecret@
    token: @wxMpToken@
  offiaccount:
    secret: @wxOffiaccountSecret@
    token: @wxOffiaccountToken@
    domain:  @wxOffiaccountToken@
  cp:
    corpId: @wxCpcorpId@
    appConfigs:
      - agentId: 1000001
        secret: secret
        token: token
        aesKey: aesKey
